### ISSUE TITLE
Reduce the number of tags with `<space><space>`

### ISSUE THREAD

**Issue by oyarsa** [MurlocCra4ler/vscode-leap#2]
The extension currently tags every whitespace in the buffer when using `<space><space>`. This behaviour differs from the neovim version, which only tags empty lines. It would be interesting if double-space highlighted the newline character for every line, but I don't see the reason to highlight _every_ whitespace.

Another consequence is that on my machine, it takes about 5 seconds to highlight the entire file when using double-space, defeating the purpose of fast jumping.

**Comment by MurlocCra4ler** [comment]
I totally agree. Perhaps I would change it so that only the first whitespace is highlighted in a chain. This would reduce the highlighting significantly, but you could still jump e.g. to the beginning of a line.

At the same time I would introduce a new setting, to give the user the option to only jump to the end of a line with <space><space>.

**Comment by oyarsa** [comment]
That sounds good. The original leap.nvim lacks a good way to do line-wise navigation, but these options to do first whitespace and newline would achieve that nicely.
